"$schema" = 'https://starship.rs/config-schema.json'

format = '${custom.repo_root}$all'

[docker_context]
detect_folders = ['.devcontainer']

[kubernetes]
disabled = false

[custom.repo_root]
command = 'basename "$(dirname "$(git rev-parse --git-common-dir)")"'
when = 'test "$(realpath "$(git rev-parse --git-dir)")" != "$(realpath "$(git rev-parse --git-common-dir)")"'
require_repo = true
symbol = "ï“ "
style = "bold bright-black"
