---
formatter:
  type: basic
  include_document_start: true
  retain_line_breaks_single: true
  scan_folded_as_literal: true
  indentless_arrays: false
  force_array_style: block
  force_quote_style: single
