[tools]
deno = "2.5.6"
go = "1.25.4"
node = "25.2.1"
python = "3.13.9"
ruby = "3.4.7"
rust = "1.91.1"

elm = "0.19.1"
go-jsonnet = "0.21.0"
perl = "5.42.0"

uv = "0.9.13"

"gem:neovim" = "0.10.0"
"npm:neovim" = "5.4.0"
"pipx:pynvim" = "0.6.0"

"npm:markuplint" = "4.14.0"
"pipx:gitlint-core" = "0.19.1"
"pipx:sqlfluff" = "3.5.0"
actionlint = "1.7.9"
dotenv-linter = "4.0.0"
editorconfig-checker = "3.6.0"
hadolint = "2.14.0"
kube-linter = "0.7.6"
markdownlint-cli2 = "0.19.1"
shellcheck = "0.11.0"
shfmt = "3.12.0"
stylua = "2.3.1"
yamlfmt = "0.20.0"
yamllint = "1.37.1"

adr-tools = "3.0.0"
k6 = "1.4.2"
redis-cli = "8.2.3"
sops = "3.11.0"
trivy = "0.67.2"

act = "0.2.82"
github-cli = "2.83.1"

aws-cli = "2.32.6"
aws-sam = "1.148.0"
ecspresso = "2.6.4"

argocd = "3.2.0"
helm = "4.0.1"
helm-diff = "3.14.1"
k9s = "0.50.16"
kubectl = "1.34.2"
kubie = "0.26.0"
kustomize = "5.8.0"
popeye = "0.22.1"
stern = "1.33.1"

packer = "1.14.3"
terraform = "1.14.0"
terraform-docs = "0.20.0"
terragrunt = "0.93.11"
tflint = "0.60.0"
tfsec = "1.28.14"
tfupdate = "0.9.3"

"npm:@playwright/mcp" = "0.0.48"
"npm:@upstash/context7-mcp" = "1.0.30"
"npm:@zed-industries/claude-code-acp" = "0.10.9"
"npm:ccusage" = "17.1.6"
"npm:mcp-hub" = "4.2.1"
"pipx:oraios/serena" = "v0.1.4"
"pipx:plamo-translate" = "1.0.5"

[settings]
idiomatic_version_file_enable_tools = ["go", "node", "ruby"]
