[tools]
deno = "2.5.6"
go = "1.25.4"
node = "24.10.0"
python = "3.14.0"
ruby = "3.4.7"
rust = "1.91.1"

elm = "0.19.1"
go-jsonnet = "0.21.0"
perl = "5.42.0"

uv = "0.9.8"

"npm:markuplint" = "4.14.0"
"pipx:gitlint-core" = "0.19.1"
"pipx:sqlfluff" = "3.5.0"
actionlint = "1.7.8"
dotenv-linter = "4.0.0"
editorconfig-checker = "3.4.1"
hadolint = "2.14.0"
kube-linter = "0.7.6"
markdownlint-cli2 = "0.18.1"
shellcheck = "0.11.0"
shfmt = "3.12.0"
stylua = "2.3.1"
yamlfmt = "0.20.0"
yamllint = "1.37.1"

adr-tools = "3.0.0"
k6 = "1.4.0"
redis-cli = "8.2.2"
sops = "3.11.0"
trivy = "0.67.2"

act = "0.2.82"
github-cli = "2.83.0"

aws-cli = "2.31.33"
aws-sam = "1.146.0"
ecspresso = "2.6.3"

argocd = "3.2.0"
helm = "3.19.0"
helm-diff = "3.13.1"
k9s = "0.50.16"
kubectl = "1.34.1"
kubie = "0.26.0"
kustomize = "5.7.1"
popeye = "0.22.1"
stern = "1.33.0"

packer = "1.14.2"
terraform = "1.13.4"
terraform-docs = "0.20.0"
terragrunt = "0.92.1"
tflint = "0.59.1"
tfsec = "1.28.14"
tfupdate = "0.9.2"

"npm:@playwright/mcp" = "0.0.44"
"npm:@upstash/context7-mcp" = "1.0.26"
"npm:@zed-industries/claude-code-acp" = "0.8.0"
"npm:ccusage" = "17.1.3"
"npm:mcp-hub" = "4.2.1"
"pipx:oraios/serena" = "v0.1.4"
"pipx:plamo-translate" = "1.0.4"

[settings]
idiomatic_version_file_enable_tools = ["go", "node", "ruby"]
