[tools]
deno = "2.6.5"
go = "1.25.6"
node = "25.3.0"
python = "3.14.2"
ruby = "4.0.1"
rust = "1.92.0"

elm = "0.19.1"
go-jsonnet = "0.21.0"
perl = "5.42.0"

uv = "0.9.26"

"gem:neovim" = "0.10.0"
"npm:neovim" = "5.4.0"
"pipx:pynvim" = "0.6.0"

"npm:markuplint" = "4.14.0"
"pipx:gitlint-core" = "0.19.1"
"pipx:sqlfluff" = "3.5.0"
actionlint = "1.7.10"
dotenv-linter = "4.0.0"
editorconfig-checker = "3.6.0"
hadolint = "2.14.0"
kube-linter = "0.8.1"
kubeconform = "0.7.0"
markdownlint-cli2 = "0.20.0"
shellcheck = "0.11.0"
shfmt = "3.12.0"
stylua = "2.3.1"
yamlfmt = "0.21.0"
yamllint = "1.38.0"

adr-tools = "3.0.0"
k6 = "1.5.0"
redis-cli = "8.4.0"
sops = "3.11.0"
trivy = "0.68.2"

"aqua:suzuki-shunsuke/pinact" = "3.8.0"
act = "0.2.84"
github-cli = "2.85.0"

"aqua:go-to-k/cls3" = "0.32.4"
aws-cli = "2.33.0"
aws-sam = "1.151.0"
ecspresso = "2.7.0"

argocd = "3.2.5"
helm = "4.0.5"
helm-diff = "3.14.1"
k9s = "0.50.18"
kube-capacity = "0.8.0"
kubectl = "1.35.0"
kubie = "0.26.1"
kustomize = "5.8.0"
popeye = "0.22.1"
stern = "1.33.1"

packer = "1.14.3"
terraform = "1.14.3"
terraform-docs = "0.21.0"
terragrunt = "0.97.2"
tflint = "0.60.0"
tfsec = "1.28.14"
tfupdate = "0.9.3"

"pipx:plamo-translate" = "1.0.5"

"npm:@zed-industries/claude-code-acp" = "0.13.0"
"npm:ccusage" = "18.0.5"
"npm:mcp-hub" = "4.2.1"

"npm:@modelcontextprotocol/server-sequential-thinking" = "2025.12.18"
"npm:@playwright/mcp" = "0.0.55"
"npm:@upstash/context7-mcp" = "2.1.0"
"npm:task-master-ai" = "0.41.0"
"pipx:awslabs.terraform-mcp-server" = "1.0.11"
"pipx:oraios/serena" = "v0.1.4"

[settings]
idiomatic_version_file_enable_tools = ["go", "node", "ruby"]
